version: '3.9'
services:
  mariadb:
    image: mariadb:10.3
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADBL_DATABASE: prisma
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
volumes:
  data:
